spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:xxx}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
      chat:
        # 启用OpenAI聊天模型
        enabled: true
        options:
          # 默认使用的模型
          model: ${OPENAI_MODEL:gpt-4o}
          # 默认温度参数 (1.0.0-M6版本使用Double类型)
          temperature: 0.7
          # 默认最大token数
          max-tokens: 2000
    deepseek:
      api-key: ${DEEPSEEK_API_KEY:sk-0720b1480e3247e8bfcab361a679e7cb}
      base-url: ${DEEPSEEK_BASE_URL:https://api.deepseek.com}
      chat:
        # 启用OpenAI聊天模型
        enabled: true
        options:
          # 默认使用的模型
          model: ${DEEPSEEK_MODEL:deepseek-chat}
          # 默认温度参数 (1.0.0-M6版本使用Double类型)
          temperature: 0.7
          # 默认最大token数
          max-tokens: 5000
